OnlineShop/OnlineShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from azbankgateways.urls import az_bank_gateways_urls
from payments.views import go_to_gateway_view, callback_gateway_view
admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('bankgateways/', az_bank_gateways_urls()),
    path('payments/', include('payments.urls', namespace='payments')),
    path('callback-gateway/', callback_gateway_view, name='callback_gateway_view'),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OnlineShop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns =[
    path('', views.detail, name='detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

OnlineShop/orders/urls.py
from django.urls import path
from . import views



app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='create'),
    path('<int:order_id>/', views.detail, name='detail'),
    path('apply/<int:order_id>/', views.coupon_apply, name='coupon_apply'),
    path('all_order/', views.show_orders, name='show_orders'),
    path('detail_order/<int:order_id>', views.show_detail_order, name='show_detail_order'),
]

OnlineShop/cart/models.py
from django.db import models

# Create your models here.

OnlineShop/cart/forms.py
from django import forms


class CartAddForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=9, label="مقدار سفارش")

OnlineShop/cart/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .cart import Cart
from shop.models import Product
from .forms import CartAddForm
from django.views.decorators.http import require_POST
# Create your views here.


def detail(request):
    cart = Cart(request)
    context = {
        'cart': cart
    }
    return render(request, 'cart/detail.html', context)


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddForm(request.POST)
    if form.is_valid():
        cd= form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'])
    return redirect('cart:detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:detail')

OnlineShop/cart/templates/cart/detail.html
{% extends 'base.html' %}
{% block content %}
    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Product</th>
                <th scope="col">Quantity</th>
                <th scope="col">Price</th>
                <th scope="col">Total_Price</th>
                <th scope="col">Remove</th>
            </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{item.product}}</td>
                <td>{{item.quantity}}</td>
                <td>{{item.price}}</td>
                <td>{{item.total_price}}</td>
                <td><a href="{% url 'cart:cart_remove' item.product.id %}">Remove</a></td>
            </tr>
        {% endfor %}
            <tr>
                <td>Total</td>
                <td colspan="4"></td>
                <td>{{cart.get_total_price}}</td>
            </tr>
        </tbody>
    </table>
    <a href="{% url 'orders:create' %}" class="btn btn-primary">Checkout</a>
{% endblock %}