OnlineShop/OnlineShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from azbankgateways.urls import az_bank_gateways_urls
from payments.views import go_to_gateway_view, callback_gateway_view
admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('bankgateways/', az_bank_gateways_urls()),
    path('payments/', include('payments.urls', namespace='payments')),
    path('callback-gateway/', callback_gateway_view, name='callback_gateway_view'),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OnlineShop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns =[
    path('', views.detail, name='detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

OnlineShop/orders/urls.py
from django.urls import path
from . import views



app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='create'),
    path('<int:order_id>/', views.detail, name='detail'),
    path('apply/<int:order_id>/', views.coupon_apply, name='coupon_apply'),
    path('all_order/', views.show_orders, name='show_orders'),
    path('detail_order/<int:order_id>', views.show_detail_order, name='show_detail_order'),
]

OnlineShop/payments/urls.py
from django.urls import path
from . import views

app_name = 'payments'

urlpatterns = [
    path('go-to-gateway/<int:order_id>/<price>/', views.go_to_gateway_view, name='go_to_gateway_view'),
    path('callback-gateway/', views.callback_gateway_view, name='callback_gateway_view'),
]

OnlineShop/orders/models.py
from django.db import models
from django.conf import settings
from shop.models import Product
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='orders')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    discount = models.IntegerField(blank=True, null=True, default=None)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return '{} - {}'.format(self.user, str(self.id))

    def get_total_price(self):
        total = sum(item.get_cost() for item in self.items.all())
        if self.discount:
            discount_price = (self.discount / 100) * total
            return int(total-discount_price)
        return total


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items')
    price = models.IntegerField()
    quantity = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity


class Coupon(models.Model):
    code = models.CharField(max_length=30, unique=True)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    discount = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.code

OnlineShop/orders/forms.py
from django import forms


class CouponForm(forms.Form):
    code = forms.CharField()

OnlineShop/orders/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.utils import timezone
from .models import Order, OrderItem, Coupon
from cart.cart import Cart
from shop.models import Product
from django.http import HttpResponse,Http404
from suds.client import Client
from django.contrib import messages
from .forms import CouponForm
from django.urls import reverse
from azbankgateways import bankfactories,models as bank_models,default_settings as settings
import logging
import time
# Create your views here.


@login_required
def order_create(request):
    cart = Cart(request)
    print(">>>>>>>>>>>>>>", cart)
    order = Order.objects.create(user=request.user)
    for item in cart:
        OrderItem.objects.create(order=order, product=item['product'], price=item['price'], quantity=item['quantity'])
        x = Product.objects.get(name=item['product'])
        x.numbers = x.numbers - item['quantity']
        x.save()
    cart.clear()
    return redirect('orders:detail', order.id)


def show_orders(request):
    user = request.user
    ords = user.orders.all()
    context = {
        'orders': ords,
    }
    return render(request, 'orders/all_order.html', context)


def show_detail_order(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    item = OrderItem.objects.filter(order=order)
    context = {
        'item': item,
        'order': order,
    }
    return render(request, 'orders/detail_orders.html', context)


@login_required
def detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    form = CouponForm()
    context = {
        'order': order,
        'form': form,
    }
    return render(request, 'orders/order.html', context)


@require_POST
def coupon_apply(request, order_id):
    now = timezone.now()
    form = CouponForm(request.POST)
    if form.is_valid():
        code = form.cleaned_data['code']
        try:
            coupon = Coupon.objects.get(code__iexact=code, valid_from__lte=now, valid_to__gte=now, active=True)
        except Coupon.DoesNotExist:
            messages.error(request, 'this coupon is invalid.', 'danger')
            return redirect('orders:detail', order_id)
        order = Order.objects.get(id=order_id)
        order.discount = coupon.discount
        order.save()
        return redirect('orders:detail', order_id)

OnlineShop/orders/templates/orders/all_order.html
{% extends 'base.html' %}
{% block content %}
    <h3>All_orders</h3>
    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">created</th>
                <th scope="col">updated</th>
                <th scope="col">paid</th>
                <th scope="col">discount</th>
            </tr>
        </thead>
        <tbody>
        {% for i in orders %}
            <tr>
                <th scope="row"><a href="{% url 'orders:show_detail_order' i.id %}">{{i.id}}</a></th>
                <td>{{i.created}}</td>
                <td>{{i.updated}}</td>
                {% if i.paid %}
                    <td style="color: #006b1b; font-family: 'B Titr'">ok</td>
                {% else %}
                    <td>ko</td>
                {% endif %}
                <td>{{i.discount}}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

OnlineShop/orders/templates/orders/detail_orders.html
{% extends 'base.html' %}
{% block content %}
    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th scope="col">product</th>
                <th scope="col">price</th>
                <th scope="col">quantity</th>
            </tr>
        </thead>
        <tbody>
        {% for i in item %}
            <tr>
                <th scope="row">{{i.product}}</th>
                <td>{{i.price}}</td>
                <td>{{i.quantity}}</td>
            </tr>
        {% endfor %}
            <tr>
                <td>Total</td>
                <td colspan="1"></td>
                <td>{{order.get_total_price}}</td>
            </tr>
        </tbody>
    </table>
{% endblock %}

OnlineShop/orders/templates/orders/order.html
{% extends 'base.html' %}
{% block content %}
    <h3>Check out</h3>
    <p>Total : {{order.get_total_price}}</p><br/><br/>
        <form action="{% url 'orders:coupon_apply' order.id %}" method="post">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Apply">
        </form>

    <br/>
    <a href="{% url 'payments:go_to_gateway_view' order.id order.get_total_price %}" class="btn btn-primary">Pay</a>
{% endblock %}