OnlineShop/OnlineShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from azbankgateways.urls import az_bank_gateways_urls
from payments.views import go_to_gateway_view, callback_gateway_view
admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('bankgateways/', az_bank_gateways_urls()),
    path('payments/', include('payments.urls', namespace='payments')),
    path('callback-gateway/', callback_gateway_view, name='callback_gateway_view'),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OnlineShop/account/urls.py
from django.urls import path
from . import views


app_name = 'account'
urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('edit/', views.edit_profile, name='edit'),
]

OnlineShop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns =[
    path('', views.detail, name='detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

OnlineShop/orders/urls.py
from django.urls import path
from . import views



app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='create'),
    path('<int:order_id>/', views.detail, name='detail'),
    path('apply/<int:order_id>/', views.coupon_apply, name='coupon_apply'),
    path('all_order/', views.show_orders, name='show_orders'),
    path('detail_order/<int:order_id>', views.show_detail_order, name='show_detail_order'),
]

OnlineShop/shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'
urlpatterns = [
    path('', views.home, name='home'),
    path('category/<slug:slug>/', views.home, name='category_filter'),
    path('<slug:slug>/', views.product_detail, name='product_detail'),
]

OnlineShop/templates/inc/message.html
{% if messages %}
    {% for msg in messages %}

        <p class="alert alert-{{msg.tags}}">{{msg}}</p>

    {% endfor %}
{% endif %}

OnlineShop/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="navbar-nav">
        <a class="nav-item nav-link active" href="{% url 'shop:home' %}">Home</a>
        {% if request.user.is_authenticated %}
            <a class="nav-item nav-link active" href="{% url 'account:logout' %}">Logout</a>
            <a class="nav-item nav-link active" href="{% url 'cart:detail' %}">your basket</a>
            <a class="nav-item nav-link active" href="{% url 'orders:show_orders' %}">show_orders</a>
            <a class="nav-item nav-link active" href="{% url 'account:edit' %}">تغییر اطلاعات کاربری</a>
            <strong style="font-family: 'B Titr'" class="nav-item nav-link active"><i>{{request.user.full_name}}</i>سلام</strong>
        {% else %}
            <a class="nav-item nav-link active" href="{% url 'account:login' %}">Login</a>
            <a class="nav-item nav-link active" href="{% url 'account:register' %}">Register</a>
        {% endif %}
    </div>
</nav>