OnlineShop/OnlineShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from azbankgateways.urls import az_bank_gateways_urls
from payments.views import go_to_gateway_view, callback_gateway_view
admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('bankgateways/', az_bank_gateways_urls()),
    path('payments/', include('payments.urls', namespace='payments')),
    path('callback-gateway/', callback_gateway_view, name='callback_gateway_view'),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OnlineShop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns =[
    path('', views.detail, name='detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

OnlineShop/shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'
urlpatterns = [
    path('', views.home, name='home'),
    path('category/<slug:slug>/', views.home, name='category_filter'),
    path('<slug:slug>/', views.product_detail, name='product_detail'),
]

OnlineShop/shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Category(models.Model):
    sub_category = models.ForeignKey('self', on_delete=models.CASCADE, related_name='scategory', null=True, blank=True)
    is_sub = models.BooleanField(default=False)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:category_filter', args=[self.slug])


class Product(models.Model):
    category = models.ManyToManyField(Category, related_name='products')
    name = models.CharField(max_length=400)
    slug = slug = models.SlugField(max_length=400, unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d')
    description = models.TextField()
    price = models.IntegerField()
    numbers = models.PositiveIntegerField(default=3)
    availabel = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.slug])

OnlineShop/shop/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category, Product
from cart.forms import CartAddForm
# Create your views here.


def home(request, slug=None):
    categories = Category.objects.filter(is_sub=False)
    products = Product.objects.filter(availabel=True)
    if slug:
        category = get_object_or_404(Category, slug=slug)
        products = products.filter(category=category)
    context = {
        'categories': categories,
        'products': products,
    }
    return render(request, 'shop/home.html', context)


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    form = CartAddForm()
    context = {
        'product': product,
        'form': form,
    }
    return render(request, 'shop/product_detail.html', context)

OnlineShop/shop/templates/shop/home.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}
    {% for category in categories %}
        <div class="btn-group">
          <a href="{{category.get_absolute_url}}" class="btn btn-danger">{{category.name}}</a>
          <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false"></button>
          <ul class="dropdown-menu">
              {% for sub in category.scategory.all %}
                    <li><a class="dropdown-item" href="{{sub.get_absolute_url}}">{{sub.name}}</a></li>
              {% endfor %}
          </ul>
        </div>
    {% endfor %}
    <br/><br/><br/>

    {% for product in products %}
        <div class="card" style="width: 18rem; display: inline-block">
            {% thumbnail  product.image "400x400" as im %}
                <img src="{{im.url}}" class="card-img-top" alt="...">
            {% endthumbnail %}
            <div class="card-body">
                <h5 class="card-title">{{product.name}}</h5>
                <p class="card-text">{{product.description|truncatechars:30}}</p>
                <a href="{{product.get_absolute_url}}" class="btn btn-primary">مشاهده جرئیات و خرید</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}

OnlineShop/shop/templates/shop/product_detail.html
{% extends 'base.html' %}
{% block content %}
    {% if product.numbers != 0 %}
        <h3>{{product.name}}</h3>
        <small>{{product.created}}</small><p> ریال {{product.price}}</p><p>{{product.numbers}}:موجودی</p><br/>
        <img src="{{product.image.url}}" alt="">
        <p>{{product.description}}</p><br/><br/>

        <form action="{% url 'cart:cart_add' product.id %}" method="post">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Add to cart">
        </form>
    {% else %}
        <p style="font-family: 'B Titr'">به علت عدم موجودی امکان خرید برای این کالا تا زمان تامین، وجود ندارد</p>
        <h3>{{product.name}}</h3>
        <small>{{product.created}}</small><p> ریال {{product.price}}</p><p>{{product.numbers}}:موجودی</p><br/>
        <img src="{{product.image.url}}" alt="">
        <p>{{product.description}}</p><br/><br/>
    {% endif %}

{% endblock %}